In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### 1. How likely is it that you roll doubles when rolling two dice?

In [18]:
exercise1 = pd.DataFrame(np.random.choice([1,2,3,4,5,6], size = (100000,2)))
exercise1.head()

0  1
0  3  1
1  3  4
2  5  1
3  4  2
4  3  2

In [19]:
check_double = exercise1[0] == exercise1[1]
check_double.mean()

0.16704

### 2.If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [22]:
# head = 1, tail = 0
exercise2 = np.random.choice([0,1], size = (100000,8))
exercise2

array([[0, 0, 1, ..., 1, 0, 1],
       [0, 1, 1, ..., 1, 1, 0],
       [1, 0, 1, ..., 1, 0, 0],
       ...,
       [0, 1, 1, ..., 0, 1, 1],
       [1, 1, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0]])

In [24]:
head_total = exercise2.sum(axis=1)
head_total

array([4, 5, 4, ..., 5, 4, 2])

In [26]:
three_heads = head_total == 3
three_heads.mean()

0.2192

In [28]:
three_more_heads = head_total > 3
three_more_heads.mean()

0.63637

### 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [29]:
# Data science = 1, Wed development = 0
exercise3 = np.random.choice([1,0,0,0], size = (100000,2))
exercise3

array([[1, 0],
       [1, 0],
       [0, 0],
       ...,
       [1, 1],
       [0, 0],
       [1, 1]])

In [33]:
data_science = exercise3.sum(axis=1)
data_science

array([1, 1, 0, ..., 2, 0, 2])

In [35]:
two_data_science = data_science == 2
two_data_science.mean()

0.06229

### 4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

In [37]:
exercise4 = np.random.normal(3, 1.5, (10000,5))
exercise4

array([[ 5.46160487,  2.05541379, -0.03630046,  3.93498872,  4.47791828],
       [-0.08408899,  2.47477429,  1.96669448,  3.8918079 ,  1.25753632],
       [ 2.49697197,  3.62966867,  6.75178508,  4.49441971,  1.63985588],
       ...,
       [ 1.99216846,  4.37825875,  1.08454203,  4.00830405,  4.01766077],
       [ 3.44597415,  0.58112661,  2.59292868,  3.95155188,  1.67200357],
       [ 4.12647095,  2.42920868,  4.39580463,  6.4795514 ,  2.13644907]])

In [39]:
exercise4 = exercise4.round()
exercise4

array([[ 5.,  2., -0.,  4.,  4.],
       [-0.,  2.,  2.,  4.,  1.],
       [ 2.,  4.,  7.,  4.,  2.],
       ...,
       [ 2.,  4.,  1.,  4.,  4.],
       [ 3.,  1.,  3.,  4.,  2.],
       [ 4.,  2.,  4.,  6.,  2.]])

In [42]:
friday = exercise4.sum(axis=1) < 17
friday.mean()

0.6725

### 5. Compare Heights
#### * Men have an average height of 178 cm and standard deviation of 8cm.
#### * Women have a mean of 170, sd = 6cm.
#### * Since you have means and standard deviations, you can use np.random.normal to generate observations.
#### * If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [60]:
man = np.random.normal(178, 8, (100000,1))
man = man.round()
man

array([[182.],
       [186.],
       [184.],
       ...,
       [172.],
       [181.],
       [194.]])

In [61]:
woman = (np.random.normal(170, 6, (100000,1))).round()
woman

array([[170.],
       [167.],
       [172.],
       ...,
       [174.],
       [169.],
       [174.]])

In [62]:
(woman > man).mean()

0.19824

### 6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

### What is the probability that we observe an installation issue within the first 150 students that download anaconda?
### How likely is it that 450 students all download anaconda without an issue?

In [65]:
fail = 1/250
fail

0.004

In [82]:
fifty_students = (np.random.random((100000, 50)) > fail).prod(axis=1).mean()
fifty_students

0.81852

In [83]:
one_hundred_students = (np.random.random((100000, 100)) > fail).prod(axis=1).mean()
one_hundred_students

0.66945

In [85]:
one_fifty_students = 1 - (np.random.random((10000, 150)) > fail).prod(axis=1).mean()
one_fifty_students

0.45289999999999997

In [88]:
four_fifty_students = (np.random.random((100000, 450)) > fail).prod(axis=1).mean()
four_fifty_students

0.16448

### 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

### How likely is it that a food truck will show up sometime this week?

In [102]:
# no food truck = 0, has food truck = 1

three_days_no_truck = (np.random.random((100000,3)) > 0.7).prod(axis=1).mean()
three_days_no_truck

0.02786

In [110]:
week = (np.random.random((100000,7)) <= 0.7).prod(axis=1).mean()
week

0.08268

### 8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [125]:
random_23_birthdays = np.random.randint(1,366,(100000,23))
random_23_birthdays

array([[160,  66, 316, ..., 217, 356, 280],
       [319, 138, 202, ..., 270, 200,  40],
       [133,  56, 343, ..., 314, 190, 360],
       ...,
       [211, 220,  95, ...,  43, 124,   4],
       [ 25, 120,  42, ...,  31,  61, 251],
       [253, 104, 139, ..., 207,  26,  70]])

In [138]:
(pd.DataFrame(random_23_birthdays).nunique(axis=1) == 22).mean()

0.36403

In [140]:
(pd.DataFrame(np.random.randint(1,366,(100000,20))).nunique(axis=1) == 19).mean()

0.32318

In [141]:
(pd.DataFrame(np.random.randint(1,366,(100000,40))).nunique(axis=1) == 39).mean()

0.25926