In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### 1. How likely is it that you roll doubles when rolling two dice?

In [34]:
exercise1 = pd.DataFrame(np.random.choice([1,2,3,4,5,6], size = (100000,2)))
exercise1.head()

0  1
0  2  2
1  3  4
2  2  1
3  5  1
4  4  4

In [19]:
check_double = exercise1[0] == exercise1[1]
check_double.mean()

0.16704

In [37]:
# review
rolls = np.random.choice([1,2,3,4,5,6], size = (100000,2))
(rolls[:,0] == rolls[:,1]).mean()

0.16544

In [42]:
roll_1 = np.random.choice([1,2,3,4,5,6], size = (100000,2))
roll_2 = np.random.choice([1,2,3,4,5,6], size = (100000,2))

(roll_1 == roll_2).mean()

0.166435

### 2.If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [22]:
# head = 1, tail = 0
exercise2 = np.random.choice([0,1], size = (100000,8))
exercise2

array([[0, 0, 1, ..., 1, 0, 1],
       [0, 1, 1, ..., 1, 1, 0],
       [1, 0, 1, ..., 1, 0, 0],
       ...,
       [0, 1, 1, ..., 0, 1, 1],
       [1, 1, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0]])

In [24]:
head_total = exercise2.sum(axis=1)
head_total

array([4, 5, 4, ..., 5, 4, 2])

In [26]:
three_heads = head_total == 3
three_heads.mean()

0.2192

In [28]:
three_more_heads = head_total > 3
three_more_heads.mean()

0.63637

### 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [29]:
# Data science = 1, Wed development = 0
exercise3 = np.random.choice([1,0,0,0], size = (100000,2))
exercise3

array([[1, 0],
       [1, 0],
       [0, 0],
       ...,
       [1, 1],
       [0, 0],
       [1, 1]])

In [33]:
data_science = exercise3.sum(axis=1)
data_science

array([1, 1, 0, ..., 2, 0, 2])

In [35]:
two_data_science = data_science == 2
two_data_science.mean()

0.06229

### 4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

In [144]:
exercise4 = np.random.normal(3, 1.5, (100000,5))
exercise4

array([[1.37581463, 3.9477646 , 1.10416262, 2.01281937, 4.19155613],
       [3.78910465, 4.95005625, 4.16125244, 6.03674082, 2.24651461],
       [3.8382579 , 2.25711925, 4.04736104, 2.54416921, 4.37110875],
       ...,
       [3.22073508, 4.46825619, 1.80874885, 3.78846559, 2.96527388],
       [2.98790944, 1.70267943, 2.4460888 , 4.67105458, 4.40288575],
       [3.04665571, 0.34818509, 5.30911426, 3.00248527, 5.56686208]])

In [145]:
exercise4 = exercise4.round()
exercise4

array([[1., 4., 1., 2., 4.],
       [4., 5., 4., 6., 2.],
       [4., 2., 4., 3., 4.],
       ...,
       [3., 4., 2., 4., 3.],
       [3., 2., 2., 5., 4.],
       [3., 0., 5., 3., 6.]])

In [146]:
friday = exercise4.sum(axis=1) < 17
friday.mean()

0.67206

### 5. Compare Heights
#### * Men have an average height of 178 cm and standard deviation of 8cm.
#### * Women have a mean of 170, sd = 6cm.
#### * Since you have means and standard deviations, you can use np.random.normal to generate observations.
#### * If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [60]:
man = np.random.normal(178, 8, (100000,1))
man = man.round()
man

array([[182.],
       [186.],
       [184.],
       ...,
       [172.],
       [181.],
       [194.]])

In [61]:
woman = (np.random.normal(170, 6, (100000,1))).round()
woman

array([[170.],
       [167.],
       [172.],
       ...,
       [174.],
       [169.],
       [174.]])

In [62]:
(woman > man).mean()

0.19824

### 6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

### What is the probability that we observe an installation issue within the first 150 students that download anaconda?
### How likely is it that 450 students all download anaconda without an issue?

In [65]:
fail = 1/250
fail

0.004

In [82]:
fifty_students = (np.random.random((100000, 50)) > fail).prod(axis=1).mean()
fifty_students

0.81852

In [83]:
one_hundred_students = (np.random.random((100000, 100)) > fail).prod(axis=1).mean()
one_hundred_students

0.66945

In [143]:
one_fifty_students = 1 - (np.random.random((100000, 150)) > fail).prod(axis=1).mean()
one_fifty_students

0.45086000000000004

In [88]:
four_fifty_students = (np.random.random((100000, 450)) > fail).prod(axis=1).mean()
four_fifty_students

0.16448

### 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

### How likely is it that a food truck will show up sometime this week?

In [102]:
# no food truck = 0, has food truck = 1

three_days_no_truck = (np.random.random((100000,3)) > 0.7).prod(axis=1).mean()
three_days_no_truck

0.02786

In [51]:
week1 = np.random.choice([1,0], p=[.7, .3], size=(10_000, 2))
(week1.sum(axis=1) >= 1).mean()

0.9105

In [44]:
# review
trucks = np.random.choice([0,1], size = (100000,3), p = [0.3, 0.7])
trucks

array([[0, 0, 1],
       [1, 1, 0],
       [1, 1, 1],
       ...,
       [0, 1, 1],
       [0, 1, 1],
       [1, 0, 1]])

In [46]:
# no truck shows in 3 days
(trucks.sum(axis=1) == 0).mean()

0.02654

In [48]:
# shows in next 2 days
trcuk_1 = np.random.choice([0,1], size = (100000,2), p = [0.3, 0.7])
trcuk_1

array([[0, 1],
       [0, 1],
       [1, 1],
       ...,
       [1, 1],
       [1, 0],
       [1, 0]])

In [49]:
(trcuk_1.sum(axis=1) > 0).mean()

0.90994

### 8. If 23 people are in the same room, what are the odds that at least two or more of them share a birthday? What if it's 20 people? 40?

In [61]:
random_23_birthdays = np.random.randint(1,366, size = (100000,23))
random_23_birthdays

array([[285, 287,  37, ..., 204,  94, 365],
       [  7,  38,  64, ...,  67, 243,  75],
       [  3, 357,   6, ...,  85,  51, 220],
       ...,
       [163,  40,  54, ...,  32,  98, 306],
       [102,  36,  41, ..., 140,  58,   4],
       [271, 270, 268, ..., 295, 268,  24]])

In [ ]:
# random_23_birthdays = np.random.choice(range(1,366),size = (100000,23))

In [54]:
(pd.DataFrame(random_23_birthdays).nunique(axis=1) < 23).mean()

0.5081

In [57]:
(pd.DataFrame(np.random.randint(1,365, size = (100000,20))).nunique(axis=1) < 20).mean()

0.41353

In [58]:
(pd.DataFrame(np.random.randint(1,365, size = (100000,40))).nunique(axis=1) < 40).mean()

0.89065

## Mage Duel!

Let's use what we've learned to play a mage duel!

Imagine your wizard has 6d4 health points and you have spells that do 6d4 damage. "6d4" means rolling six 4-sided dice and summing the result.

Your opposing mage has 4d6 health points and spells that do 4d6. "4d6" means rolling four six-sided dice and summing the result.

Exercises
Simulate mage duels to answer who is the more powerful mage?

1. Before running simulations, do you have a hypothesis of which mage will win? Do you have a hunch? Write it down. This is your first exercise.
2. Simulate 10 mage duels. Is there a clear winner? Run that 10 duel simulation again. Was the answer similar?
3. Do the results change much at 100 duels?
4. Now, simulate 10,000 mage duels. Is there a clear winner?

In [15]:
# mage1 = 6d4 (rolling six 4-sided dice), mage2 = 4d6, (rolling four six-sided dice)
# exercises 1
n = 100000
mage1_health = np.random.choice([1,2,3,4], size = (n,6))
mage1_spell = np.random.choice([1,2,3,4], size = (n,6))

In [16]:
mage2_health = np.random.choice([1,2,3,4,5,6], size = (n,4))
mage2_spell = np.random.choice([1,2,3,4,5,6], size = (n,4))

In [19]:
mage1_servival = mage2_spell.sum(axis=1) - mage1_health.sum(axis=1)
(mage1_servival > 0).mean()

0.3679

In [21]:
mage2_servival = mage1_spell.sum(axis=1) - mage2_health.sum(axis=1)
(mage2_servival > 0).mean()

0.54573

In [ ]:
# exercise 2
